---
# This is a sample Swagger spec, describing a simple API as a starting point.  
swagger: "2.0"
info:
  description: Api Agenda Virtual
  version: 1.0.0
  title: Api Agenda Virtual
host: gihub.com.marcelofelipesilva.api_agenda_virtual
basePath: /api
schemes:
- http

# Tags organize operations into groups for presentation in the Swagger UI.
# Each tag has an optional description, which the Swagger UI will display in 
# the tag group header.
tags:
- name: Api Agenda Virtual
  description: An individual Tax Filing record, accessed by its ID

paths:

  # Each Path Item Object describes a resource, containing a set of operations
  # at a specified path.  The Path Item object can define parameters and 
  # responses common all of its contained operations.
  /taxFilings/{id}:

    # Operations are identified by an HTTP method.  
    get:
      tags:
      - TaxFilingObject
      description: Retrieves a tax filing having the specified id.
      operationId: getTaxFiling
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: ID of the requested TaxFiling
        required: true
        type: string
      responses:
        200:
          description: Successful response, with a representation of the Tax Filing.
          schema:
            # Reference to a Schema Object described in 'definitions' section
            $ref: "#/definitions/TaxFilingObject"
          examples:
            # Example message, keyed by media type
            application/json :
              {
                filingID : "1234",
                jurisdiction : Federal,
                year : "2015-10-02",
                currency : EUR,
                grossIncome : 74832,
                taxLiability : 15640
              }
        404:
          description: The requested tax filing was not found.

# The definitions section contains a set of named Schema Objects.  Each schema
# object describes a reusable data type, which can be reference by name.
definitions:
  TaxFilingObject:
    type: object
    description: An individual Tax Filing record.
    properties:
      filingID:
        type: string
      jurisdiction:
        type: string
      year:
        type: string
        format: date
      period:
        type: integer
      currency:
        type: string
      grossIncome:
        type: number
      taxLiability:
        type: number
      taxpayer:
        type: object
